apiVersion: v1
kind: Service
metadata:
  name: db #since in src code it looks for db and redis
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432  #pod port
  selector:
    #copy from pod def file labels
    name: postgres-pod
    app: demo-voting-app