apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80  #pod port
      nodePort: 30005
  selector:
    #copy from pod def file labels
    name: result-app-pod
    app: demo-voting-app