apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort #without this it will work as clusterIp internal service
  ports:
    - port: 80
      targetPort: 80  #pod port
      nodePort: 33004 #to access from user end
  selector:
    #copy from pod def file labels
    name: voting-app-pod
    app: demo-voting-app